// Generated by https://quicktype.io

export interface IServicio {
    id:          number;
    titulo:      string;
    categoria:   string;
    descripcion1: string; //Verificar que todos esten correctamente al asociarlos
    imagen:      string;
    tecnologias: string[];
}